# Generated by Django 4.0.5 on 2022-06-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_stat_options_remove_pokemon_evolution_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'PokemonType',
                'verbose_name_plural': 'PokemonTypes',
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='pokedex.pokemontype'),
        ),
    ]
